server:
  port: 0

spring:
  cloud:
    consul:
      host: consul
      discovery:
        instanceId: productService
        health-check-interval: 5s
      config:
        management:
          enabled: true
    stream:
      bindings:
        output:
          binder: kafka
          destination: cloudEX
management:
  security:
    enabled: false
